#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Mar 22, 2018 11:48:51 PM

import sys
import time
import threading
from threading import Timer
import time
from processing.qr import get_qr_code
from processing.ocr import get_date_time_from_screen
from processing.scan import scan_image
import cv2
import requests
import datetime
from pprint import pprint
from colorama import Fore, Back, Style
from colorama import init
from termcolor import colored
import winsound

camera = cv2.VideoCapture(0)
# camera.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0)
# camera.set(cv2.CAP_PROP_EXPOSURE, 0.1) 
camera.set(cv2.CAP_PROP_EXPOSURE, -2.0) 
while True:
    
    ret, frame = camera.read()

    print camera.get(cv2.CAP_PROP_EXPOSURE)
    print "\t" + str(camera.get(cv2.CAP_PROP_AUTO_EXPOSURE))
    cv2.imshow("video", frame)

    # cv2.waitKey(0)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

camera.release()
cv2.destoyAllWindows()